jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Hugging Face Hub
        run: pip install --upgrade huggingface_hub

      - name: Set HF Token
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: echo "HF_TOKEN is set"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/sanskarjayale/student-exam-performance hf-space
          cp -r app.py Dockerfile requirements.txt templates static hf-space/
          cd hf-space
          git add .
          git commit -m "Update from GitHub main branch" || echo "No changes to commit"
          git push
